#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# HospitalityOS — Project Setup Script
# Run: bash setup.sh
# ─────────────────────────────────────────────────────────────────

PROJECT="hospitality-os"

echo "🏨 Creating HospitalityOS project..."

# 1. Scaffold Next.js app
npx create-next-app@latest $PROJECT \
  --typescript \
  --tailwind \
  --eslint \
  --app \
  --src-dir=false \
  --import-alias="@/*" \
  --no-git

cd $PROJECT

# 2. Install dependencies
echo "📦 Installing dependencies..."
npm install \
  @supabase/supabase-js \
  @supabase/auth-helpers-nextjs \
  googleapis \
  resend \
  lucide-react \
  clsx

npm install -D \
  @types/node \
  @types/react \
  @types/react-dom

# 3. Create folder structure
echo "📁 Creating folder structure..."
mkdir -p app/dashboard/_components
mkdir -p app/dashboard/_data
mkdir -p config
mkdir -p lib
mkdir -p app/api/payroll
mkdir -p app/api/drive

# 4. Create .env.local with placeholders
cat > .env.local << 'EOF'
# ── Supabase ───────────────────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_service_role_key

# ── Google Drive (Service Account) ────────────────────────
GOOGLE_SERVICE_ACCOUNT_EMAIL=your-service-account@project.iam.gserviceaccount.com
GOOGLE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nYOUR_KEY_HERE\n-----END PRIVATE KEY-----"
GOOGLE_DRIVE_FOLDER_ID=your_google_drive_folder_id

# ── Email (Resend) ─────────────────────────────────────────
RESEND_API_KEY=re_your_resend_api_key
EMAIL_FROM=noreply@yourbusiness.com

# ── App ────────────────────────────────────────────────────
NEXT_PUBLIC_APP_NAME="HospitalityOS"
CLIENT_ID=client_001
EOF

# 5. Create client config file
cat > config/client.config.ts << 'EOF'
// ─────────────────────────────────────────────────────────────────────────────
// client.config.ts
// Single-client mode: values come from .env
// Multi-client mode (future): load this from Supabase per client
// ─────────────────────────────────────────────────────────────────────────────
export const clientConfig = {
  clientId:       process.env.CLIENT_ID ?? "client_001",
  businessName:   process.env.NEXT_PUBLIC_APP_NAME ?? "My Hotel",
  driveMode:      (process.env.DRIVE_MODE ?? "self_hosted") as "self_hosted" | "client_oauth",
  driveFolderId:  process.env.GOOGLE_DRIVE_FOLDER_ID ?? "",
  accountantEmail: process.env.ACCOUNTANT_EMAIL ?? "",
  alerts: {
    inspectionDays: 30,
    licenseDays:    60,
    payrollWeeks:   2,
  },
};
EOF

# 6. Create Supabase client lib
cat > lib/supabase.ts << 'EOF'
import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);
EOF

# 7. Create Google Drive lib
cat > lib/google-drive.ts << 'EOF'
import { google } from "googleapis";
import { clientConfig } from "@/config/client.config";

// Returns an authenticated Drive client
export async function getDriveClient() {
  const auth = new google.auth.GoogleAuth({
    credentials: {
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key:  process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
    },
    scopes: ["https://www.googleapis.com/auth/drive.readonly"],
  });
  return google.drive({ version: "v3", auth });
}

// List files in the configured Drive folder
export async function listDriveFiles(subfolder?: string) {
  const drive    = await getDriveClient();
  const folderId = subfolder ?? clientConfig.driveFolderId;
  const res = await drive.files.list({
    q: `'${folderId}' in parents and trashed=false`,
    fields: "files(id, name, mimeType, modifiedTime, webViewLink)",
    orderBy: "modifiedTime desc",
  });
  return res.data.files ?? [];
}
EOF

# 8. Create Resend email lib
cat > lib/email.ts << 'EOF'
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

interface PayrollEmailData {
  to:        string;
  period:    string;
  employees: { name: string; role: string; payType: string; rate: number; hours: number | null }[];
  total:     number;
}

export async function sendPayrollEmail({ to, period, employees, total }: PayrollEmailData) {
  const lines = employees.map(e =>
    e.payType === "hourly"
      ? `• ${e.name} (${e.role}) — ${e.hours} hrs @ $${e.rate}/hr = $${(e.rate * (e.hours ?? 0)).toLocaleString()}`
      : `• ${e.name} (${e.role}) — Biweekly $${e.rate.toLocaleString()}`
  ).join("\n");

  return resend.emails.send({
    from:    process.env.EMAIL_FROM!,
    to,
    subject: `Payroll Request — ${period}`,
    text:    `Please process payroll for ${period}:\n\n${lines}\n\nTotal: $${total.toLocaleString()}\n\nGenerated by HospitalityOS`,
  });
}
EOF

echo ""
echo "✅ HospitalityOS scaffold complete!"
echo ""
echo "📋 Next steps:"
echo "  1. Copy your dashboard files into app/dashboard/"
echo "  2. Fill in .env.local with your real keys"
echo "  3. Run: npm run dev"
echo "  4. Open: http://localhost:3000/dashboard"