"use client";
import { useState, useEffect } from "react";
import { Card, PageHeader, useIsMobile } from "./shared";
import { MOCK } from "../_data/mock";

interface EmployeePayState {
  included: boolean;
  hours:    number;
  rate:     number;
  biweekly: number;
}

function calcPay(e: typeof MOCK.employees[0], state: EmployeePayState) {
  return e.payType === "hourly" ? state.hours * state.rate : state.biweekly;
}

function buildEmailBody(accountant: string, period: string, employees: typeof MOCK.employees, payStates: Record<number, EmployeePayState>, total: number) {
  const included = employees.filter(e => payStates[e.id]?.included);
  const lines = included.map(e => {
    const state = payStates[e.id];
    const pay   = calcPay(e, state);
    const orig  = e.payType === "hourly" ? e.rate * (e.hours ?? 0) : e.rate;
    return `• ${e.name} (${e.role}) — ${e.payType === "hourly" ? `${state.hours} hrs @ $${state.rate}/hr` : "Biweekly"} = $${pay.toLocaleString()}${pay !== orig ? " (changed)" : ""}`;
  }).join("\n");
  return `To: ${accountant}\nSubject: Payroll Request — ${period}\n\nHi,\n\nPlease process payroll for ${period}:\n\n${lines}\n\nTotal: $${total.toLocaleString()}\n\nGenerated by HospitalityOS Dashboard`;
}

export default function PayrollPage() {
  const isMobile = useIsMobile();
  const [accountant, setAccountant] = useState("accountant@yourbusiness.com");
  const [period, setPeriod]         = useState("Apr 8 – Apr 22, 2026");
  const [sent, setSent]             = useState(false);
  const [sending, setSending]       = useState(false);
  const [emailBody, setEmailBody]   = useState("");

  const [payStates, setPayStates] = useState<Record<number, EmployeePayState>>(
    Object.fromEntries(MOCK.employees.map(e => [e.id, {
      included: true, hours: e.hours ?? 0, rate: e.rate, biweekly: e.rate,
    }]))
  );

  const updateState = (id: number, patch: Partial<EmployeePayState>) =>
    setPayStates(prev => ({ ...prev, [id]: { ...prev[id], ...patch } }));

  const includedEmployees = MOCK.employees.filter(e => payStates[e.id]?.included);
  const total = includedEmployees.reduce((sum, e) => sum + calcPay(e, payStates[e.id]), 0);

  useEffect(() => {
    setEmailBody(buildEmailBody(accountant, period, MOCK.employees, payStates, total));
  }, [accountant, period, payStates, total]);

  const handleSend = async () => {
    setSending(true);
    await new Promise(r => setTimeout(r, 1000));
    setSending(false);
    setSent(true);
  };

  return (
    <div>
      <PageHeader title="💸 Payroll Email" />

      <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 16 }}>

        {/* Left — controls */}
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Card>
            <label style={LABEL}>Accountant Email</label>
            <input value={accountant} onChange={e => setAccountant(e.target.value)} style={INPUT} />
            <label style={{ ...LABEL, marginTop: 16 }}>Pay Period</label>
            <input value={period} onChange={e => setPeriod(e.target.value)} style={INPUT} />
          </Card>

          <Card style={{ padding: 0, overflow: "hidden" }}>
            <div style={{ padding: "12px 16px", background: "#0f172a", borderBottom: "1px solid #334155" }}>
              <div style={{ color: "#64748b", fontSize: 11, fontWeight: 700, textTransform: "uppercase" }}>
                Employees
              </div>
            </div>

            {MOCK.employees.map(e => {
              const state    = payStates[e.id];
              const isHourly = e.payType === "hourly";
              const pay      = calcPay(e, state);
              const origPay  = isHourly ? e.rate * (e.hours ?? 0) : e.rate;
              const changed  = pay !== origPay;

              return (
                <div key={e.id} style={{
                  padding: "12px 16px", borderBottom: "1px solid #334155",
                  opacity: state.included ? 1 : 0.4,
                  background: state.included ? "transparent" : "#0a0f1a",
                }}>
                  {/* Name row */}
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                      <input type="checkbox" checked={state.included}
                        onChange={() => updateState(e.id, { included: !state.included })}
                        style={{ width: 16, height: 16, cursor: "pointer", accentColor: "#7c6af7" }}
                      />
                      <div>
                        <div style={{ color: "#f1f5f9", fontWeight: 600, fontSize: 14 }}>{e.name}</div>
                        <div style={{ color: "#64748b", fontSize: 12 }}>{e.role} · {isHourly ? "Hourly" : "Salaried"}</div>
                      </div>
                    </div>
                    <div style={{ color: changed ? "#7c6af7" : "#4ade80", fontWeight: 700, fontSize: 15 }}>
                      ${pay.toLocaleString()}
                    </div>
                  </div>

                  {/* Input row */}
                  <div style={{ display: "flex", gap: 8, marginLeft: 26 }}>
                    {isHourly ? (
                      <>
                        <div style={{ flex: 1 }}>
                          <div style={{ color: "#475569", fontSize: 10, fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Hours</div>
                          <input type="number" value={state.hours} disabled={!state.included}
                            onChange={ev => updateState(e.id, { hours: parseFloat(ev.target.value) || 0 })}
                            style={{ ...SMALL_INPUT, borderColor: state.hours !== (e.hours ?? 0) ? "#7c6af7" : "#334155", color: state.hours !== (e.hours ?? 0) ? "#7c6af7" : "#f1f5f9" }}
                          />
                        </div>
                        <div style={{ flex: 1 }}>
                          <div style={{ color: "#475569", fontSize: 10, fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Rate $</div>
                          <input type="number" value={state.rate} disabled={!state.included}
                            onChange={ev => updateState(e.id, { rate: parseFloat(ev.target.value) || 0 })}
                            style={{ ...SMALL_INPUT, borderColor: state.rate !== e.rate ? "#7c6af7" : "#334155", color: state.rate !== e.rate ? "#7c6af7" : "#f1f5f9" }}
                          />
                        </div>
                      </>
                    ) : (
                      <div style={{ flex: 1 }}>
                        <div style={{ color: "#475569", fontSize: 10, fontWeight: 600, textTransform: "uppercase", marginBottom: 4 }}>Biweekly Amount $</div>
                        <input type="number" value={state.biweekly} disabled={!state.included}
                          onChange={ev => updateState(e.id, { biweekly: parseFloat(ev.target.value) || 0 })}
                          style={{ ...SMALL_INPUT, borderColor: changed ? "#7c6af7" : "#334155", color: changed ? "#7c6af7" : "#4ade80", fontWeight: 700 }}
                        />
                      </div>
                    )}
                  </div>
                </div>
              );
            })}

            <div style={{ display: "flex", justifyContent: "space-between", padding: "14px 16px", background: "#0f172a" }}>
              <div style={{ color: "#94a3b8", fontSize: 13 }}>{includedEmployees.length} of {MOCK.employees.length} included</div>
              <div style={{ color: "#7c6af7", fontWeight: 800, fontSize: 16 }}>Total: ${total.toLocaleString()}</div>
            </div>
          </Card>
        </div>

        {/* Right — email preview */}
        <Card style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div style={{ color: "#94a3b8", fontSize: 13, fontWeight: 600 }}>EMAIL PREVIEW</div>
            <button onClick={() => setEmailBody(buildEmailBody(accountant, period, MOCK.employees, payStates, total))}
              style={{ background: "#1e293b", border: "1px solid #334155", color: "#64748b", borderRadius: 6, padding: "4px 12px", cursor: "pointer", fontSize: 12 }}>
              ↺ Reset
            </button>
          </div>
          <textarea value={emailBody} onChange={e => setEmailBody(e.target.value)}
            style={{ flex: 1, minHeight: isMobile ? 200 : 360, background: "#0f172a", border: "1px solid #334155", borderRadius: 8, padding: 16, color: "#cbd5e1", fontSize: 13, lineHeight: 1.8, resize: "vertical", fontFamily: "monospace", boxSizing: "border-box", width: "100%" }}
          />
          {sent ? (
            <div style={{ textAlign: "center", color: "#4ade80", fontWeight: 700, padding: 12 }}>✅ Email Sent!</div>
          ) : (
            <button onClick={handleSend} disabled={sending || includedEmployees.length === 0}
              style={{ width: "100%", background: includedEmployees.length === 0 ? "#1e293b" : sending ? "#4c3d9e" : "#7c6af7", color: includedEmployees.length === 0 ? "#475569" : "#fff", border: "none", borderRadius: 8, padding: "12px", cursor: includedEmployees.length === 0 ? "not-allowed" : "pointer", fontWeight: 700, fontSize: 15 }}>
              {sending ? "Sending..." : includedEmployees.length === 0 ? "Select at least one employee" : `📧 Send Payroll Email (${includedEmployees.length})`}
            </button>
          )}
        </Card>
      </div>
    </div>
  );
}

const LABEL: React.CSSProperties = { display: "block", color: "#94a3b8", fontSize: 13, fontWeight: 600, marginBottom: 8 };
const INPUT: React.CSSProperties = { width: "100%", background: "#0f172a", border: "1px solid #334155", borderRadius: 8, padding: "10px 14px", color: "#f1f5f9", fontSize: 14, boxSizing: "border-box" };
const SMALL_INPUT: React.CSSProperties = { width: "100%", background: "#0f172a", border: "1px solid #334155", borderRadius: 8, padding: "6px 8px", fontSize: 13, boxSizing: "border-box" as const, color: "#f1f5f9" };